# Generated by Django 3.2.9 on 2021-11-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.CharField(max_length=255)),
                ('start_period', models.DateField()),
                ('end_period', models.DateField()),
                ('compiled_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('passive_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('passive_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField()),
                ('account_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.accountclass')),
                ('account_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.accountledger')),
                ('closing_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.closingbalance')),
                ('opening_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.openingbalance')),
                ('turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.turnover')),
            ],
        ),
    ]
